### ISSUE TITLE
Bug with TransformerDecoderLayer

### ISSUE THREAD

**Issue by EliLichtblau** [ClashLuke/TrueGrad#1]
Version of tools.
```py
torch.__version__ == '1.12.1'
```

I tried to construct an arbitrarily simple standard decoder, I didn't include an embedding layer to remove complexity so I just generated data of the expected shape in the forward pass. (I included a linear at the end mostly because I forgot to remove it - my original model had it.)

```python
class Transformer(torch.nn.Module):
    def __init__(self, num_embeddings: int, d_model: int):
        super().__init__()
        self.d_model = d_model
        self.num_embeddings = num_embeddings


        self.decoder_layer = torch.nn.TransformerDecoderLayer(self.d_model, nhead=1,
                                        dropout=0.1, dim_feedforward=64)

        self.linear = torch.nn.Linear(
            self.d_model, self.num_embeddings, bias=False)


    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.decoder_layer.forward(x,x) # sending x to both is wrong, just for simplicity
        return self.linear(x)
```
And called the model as follows: 
```py
batch_size = 100
seq_len = 3
embedding_dim = 128
num_embeddings = 97


sample_input = torch.rand((batch_size, seq_len, embedding_dim)).float()
sample_output = torch.rand((batch_size, seq_len)).long()
model = Transformer(num_embeddings, 128)
patch_model(model)
optim = TGAdamW(model.parameters())

out = model(sample_input).transpose(-2, -1)
loss = F.cross_entropy(out, sample_output)
loss.backward()
optim.step()
```

This resulted in the following error:
```
File "<local file path>/TrueGrad/truegrad/optim.py", line 30, in step
    raise ValueError(f"Parameter of type {type(p)}, shape {list(p.size())} doesn't have `square_grad` attribute. "
ValueError: Parameter of shape [384, 128] doesn't have `square_grad` attribute. Make sure to use truegrad.utils.patch_model() or truegrad.nn for all optimized parameters.
```
We can confirm that this parameter is a truegrad parameter by modifying the ValueError to emit the type of the object getting the following error message.
```
raise ValueError(f"Parameter of type {type(p)}, shape {list(p.size())} doesn't have `square_grad` attribute. "
ValueError: Parameter of type <class 'truegrad.nn.TrueGradParameter'>, shape [384, 128] doesn't have `square_grad` attribute. Make sure to use truegrad.utils.patch_model() or truegrad.nn for all optimized parameters.
```

Possibly explanations?
Playing around a little with the following function
```python
def check(model: torch.nn.Module):
    good_params = []
    print("BROKEN PARAMS:\n")
    for name, param in model.named_parameters():
        if not hasattr(param, "square_grad") and hasattr(param, "grad")  :
            print(f"\t {name} {param.shape}")
        else:
            good_params.append((name, param))
    print(f"\n\nGOOD PARAMS: \n")
    for name, param in good_params:
        print(f"\t{name} {param.shape}")
```
We can run this after loss.backward() but before optim.step() and we get the following results:
```
BROKEN PARAMS:

	 decoder_layer.self_attn.in_proj_weight torch.Size([384, 128])
	 decoder_layer.self_attn.in_proj_bias torch.Size([384])
	 decoder_layer.self_attn.out_proj.weight torch.Size([128, 128])
	 decoder_layer.self_attn.out_proj.bias torch.Size([128])
	 decoder_layer.multihead_attn.in_proj_weight torch.Size([384, 128])
	 decoder_layer.multihead_attn.in_proj_bias torch.Size([384])
	 decoder_layer.multihead_attn.out_proj.weight torch.Size([128, 128])
	 decoder_layer.multihead_attn.out_proj.bias torch.Size([128])


GOOD PARAMS:

	decoder_layer.linear1.weight torch.Size([64, 128])
	decoder_layer.linear1.bias torch.Size([64])
	decoder_layer.linear2.weight torch.Size([128, 64])
	decoder_layer.linear2.bias torch.Size([128])
	decoder_layer.norm1.weight torch.Size([128])
	decoder_layer.norm1.bias torch.Size([128])
	decoder_layer.norm2.weight torch.Size([128])
	decoder_layer.norm2.bias torch.Size([128])
	decoder_layer.norm3.weight torch.Size([128])
	decoder_layer.norm3.bias torch.Size([128])
	linear.weight torch.Size([97, 128])
```
Both multihead_attn and self_attn are instances of MultiheadAttention, its also not really clear to me why attributes of both objects. i.e. "k_proj_weight" appear in neither but they are Nones. I'm probably going to spend more time looking into this but I hope this helps you debug as well. This is all the information I have at the moment.

**Comment by ClashLuke** [comment]
Thank you for the detailed bug report!\
It seems the issue stems from `multi_head_attention_forward` being a fused function that returns a tuple of outputs. As tuples of tensors aren't recognized as tensors by TrueGradParameter, it doesn't modify the backward pass to add the square_grad.\
While it'd be possible to solve the tuple issue, I'm afraid that would only uncover more problems.

To compute the `square_grad` attribute, truegrad does a second (inner) backward pass using `torch.autograd.backward(f(x^2), dy^2)`. While that works well for simple operations that directly access the parameter, like linear or convolution, it works horribly for fused layers. For example, `LayerNorm(input^2, scale, shift)`, or in this case, `attention(x^2)`, gives very different results from `( (x-x.mean())/x.std() )^2 * scale + shift` (which is what we need).

The best way I see of tackling this issue is to
1) extend the readme with an explicit warning about fused functions
2) fix the tuple issue
3) port more of torch.nn to truegrad.nn

What do you think?

**Comment by EliLichtblau** [comment]
I 100% agree with the steps. Technically, you can "fix" the tuple issue by having the forward pass for wrap emit x not torch.zeros_like(x) but I don't think this solution will do backprop correctly and failing silently seems like a worse solution. I do think porting as much of torch.nn to truegrad.nn seems like the best way forward. If this just involves looking at the torch C++ implementation and copying the backprop code and squaring when necessary I can start doing this as well. 

It might be worth while to also have patch_model do a check that looks for Modules that do fused functions and fail loudly if any are encountered.

**Comment by ClashLuke** [comment]
I can port the rest of torch.nn by the weekend, but I'm unsure how to detect fused functions. Could you have a look at that?

**Comment by EliLichtblau** [comment]
If you can port all torch.nn by the weekend thats insane, uh but yes I can look into how to detect fused functions. I'll try to think about it in a programmatic/mathematical way and see if I can think of/find anything clever. The fallback would be sort of a blacklist of fused functions in torch.nn.functional that do fused ops and then hooking into a python LSP to inspect the forward methods for use of blacklist operations. 

If you port all of torch.nn though it seems like patch_model would be pointless? You could just swap torch.nn for truegrad.nn, do you really plan to implement the entirety of torch.nn?

**Comment by ClashLuke** [comment]
We'll still need something like `patch_model` for off-the-shelf models like torchvision and huggingface transformers. However, it seems like patching the parameters is incredibly difficult. For example, `TrueGradParameter(x).reshape(-1) * input` would link `reshape` as torch function instead of the multiplication. It seems like we have to find the last operations with a data axis like batch, sequence, and width.\
Additionally, inspecting the python code won't work for a general case, as many projects (such as [xformers](https://github.com/facebookresearch/xformers/)) depend on fused cuda kernels.\
The most straightforward way forward would be to provide a ported version of `torch.nn`, write a `patch_torch_nn` function, and add a `fall_back_to_adam` flag in TGAdamW so mixed models can exist.

However, if we have to patch and reimplement all of `torch.nn` anyway, we can fall back to [backpack](https://github.com/f-dangel/backpack). Backpack contains reimplemented torch modules and has functions to compute the `square_grad` attribute.

**Comment by ClashLuke** [comment]
Added backpack support in https://github.com/ClashLuke/TrueGrad/commit/0a14e3877db30b25f89b6506bbd365386f7a70e4 / 0.1.0. We'll probably need a more extensive` truegrad.nn.functional` rather than a larger `truegrad.nn`, so I'll work on that tomorrow.

**Comment by ClashLuke** [comment]
Truegrad 2.0.0 gives the following output using the `truegrad.utils.patch_torch` backend:
```
BROKEN PARAMS:



GOOD PARAMS: 

	decoder_layer.self_attn.in_proj_weight torch.Size([384, 128])
	decoder_layer.self_attn.in_proj_bias torch.Size([384])
	decoder_layer.self_attn.out_proj.weight torch.Size([128, 128])
	decoder_layer.self_attn.out_proj.bias torch.Size([128])
	decoder_layer.multihead_attn.in_proj_weight torch.Size([384, 128])
	decoder_layer.multihead_attn.in_proj_bias torch.Size([384])
	decoder_layer.multihead_attn.out_proj.weight torch.Size([128, 128])
	decoder_layer.multihead_attn.out_proj.bias torch.Size([128])
	decoder_layer.linear1.weight torch.Size([64, 128])
	decoder_layer.linear1.bias torch.Size([64])
	decoder_layer.linear2.weight torch.Size([128, 64])
	decoder_layer.linear2.bias torch.Size([128])
	decoder_layer.norm1.weight torch.Size([128])
	decoder_layer.norm1.bias torch.Size([128])
	decoder_layer.norm2.weight torch.Size([128])
	decoder_layer.norm2.bias torch.Size([128])
	decoder_layer.norm3.weight torch.Size([128])
	decoder_layer.norm3.bias torch.Size([128])
	linear.weight torch.Size([97, 128])
```

Complete code:
```PYTHON
import torch
from torch.nn import functional as F

from truegrad.optim import TGAdamW
from truegrad.utils import patch_torch

patch_torch()


class Transformer(torch.nn.Module):
    def __init__(self, num_embeddings: int, d_model: int):
        super().__init__()
        self.d_model = d_model
        self.num_embeddings = num_embeddings

        self.decoder_layer = torch.nn.TransformerDecoderLayer(self.d_model, nhead=1,
                                                              dropout=0.1, dim_feedforward=64)

        self.linear = torch.nn.Linear(
                self.d_model, self.num_embeddings, bias=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.decoder_layer.forward(x, x)  # sending x to both is wrong, just for simplicity
        return self.linear(x)


batch_size = 100
seq_len = 3
embedding_dim = 128
num_embeddings = 97

sample_input = torch.rand((batch_size, seq_len, embedding_dim)).float()
sample_output = torch.rand((batch_size, seq_len)).long()
model = Transformer(num_embeddings, 128)
optim = TGAdamW(model.parameters())

out = model(sample_input).transpose(-2, -1)
loss = F.cross_entropy(out, sample_output)
loss.backward()

good_params = []
print("BROKEN PARAMS:\n")
for name, param in model.named_parameters():
    if not hasattr(param, "sum_grad_squared") and hasattr(param, "grad"):
        print(f"\t {name} {param.shape}")
    else:
        good_params.append((name, param))
print(f"\n\nGOOD PARAMS: \n")
for name, param in good_params:
    print(f"\t{name} {param.shape}")
```

**Comment by EliLichtblau** [comment]
Wow, sorry I haven't looked at anything yet, busy with family stuff, this is super impressive. Thank you so much for solving this so fast though, wow.

**Comment by ClashLuke** [comment]
All good. Take care, and let me know if there are any other issues.
